### ISSUE TITLE
layout listing missing

### ISSUE THREAD

**Issue by ITotalJustice** [suchmememanyskill/themezer-nx#10]
on the website, there's a way to list layouts only, here is a get request to do that:
https://api.themezer.net/?query=query($page:Int,$limit:Int,$sort:String,$order:String,$query:String){layoutList(page:$page,limit:$limit,sort:$sort,order:$order,query:$query){id,uuid,creator{id,display_name},details{name,description,color},target,last_updated,dl_count,like_count}}&variables={"page":1,"limit":10,"sort":"updated","order":"desc","query":null}

to request an image of the layout, you have to use the uuid:
https://api.themezer.net/cdn/layouts/uuid-here/overlay.png

actual example:
https://api.themezer.net/cdn/layouts/a0af39c7-676b-4cd1-a0c9-20f16cc4e7cd/overlay.png

**Comment by suchmememanyskill** [comment]
Why would it be useful to list layouts?

**Comment by ITotalJustice** [comment]
well i thought it was basically a plain theme, just the layout changed. I realise now its actually a template for other themes 🤣
