### ISSUE TITLE
Add to HBstore

### ISSUE THREAD

**Issue by Shidapu** [suchmememanyskill/themezer-nx#3]
Please add your application to the HBstore. For ease of access and ease of updating.

**Comment by suchmememanyskill** [comment]
i was already planning to do this but last time i tried it didn't want to submit it. I'll see if i can retry shortly

**Comment by suchmememanyskill** [comment]
I still can't submit themes it seems. i'll see if i can contact 4tu about this

**Comment by suchmememanyskill** [comment]
i submitted the app to the hbappstore. It may be a while till they accept it though
