### ISSUE TITLE
nsfw field missing

### ISSUE THREAD

**Issue by ITotalJustice** [suchmememanyskill/themezer-nx#9]
hi! you can add nsfw to the get command to have it list nsfw themes. As you don't have the field in the request, all those themes are filtered out. You can check the the total count here

### with nsfw
https://api.themezer.net/?query=query($nsfw:Boolean,$page:Int,$limit:Int,$sort:String,$order:String,$query:String){packList(nsfw:$nsfw,page:$page,limit:$limit,sort:$sort,order:$order,query:$query){id,creator{display_name},details{name,description},last_updated,dl_count,like_count,themes{id,creator{display_name},details{name,description},last_updated,dl_count,like_count,target,preview{original,thumb}}}}&variables={"nsfw":true,"page":1,"limit":10,"sort":"updated","order":"desc","query":null}

### without nsfw
https://api.themezer.net/?query=query($nsfw:Boolean,$page:Int,$limit:Int,$sort:String,$order:String,$query:String){packList(nsfw:$nsfw,page:$page,limit:$limit,sort:$sort,order:$order,query:$query){id,creator{display_name},details{name,description},last_updated,dl_count,like_count,themes{id,creator{display_name},details{name,description},last_updated,dl_count,like_count,target,preview{original,thumb}}}}&variables={"nsfw":false,"page":1,"limit":10,"sort":"updated","order":"desc","query":null}

this works for all requests, eg:
https://api.themezer.net/?query=query($nsfw:Boolean,$target:String,$page:Int,$limit:Int,$sort:String,$order:String,$query:String){themeList(nsfw:$nsfw,target:$target,page:$page,limit:$limit,sort:$sort,order:$order,query:$query){id,creator{display_name},details{name,description},last_updated,dl_count,like_count,target,preview{original,thumb}}}&variables={"nsfw":true,"target":null,"page":1,"limit":10,"sort":"updated","order":"desc","query":null}

**Comment by suchmememanyskill** [comment]
Sorry, i'm unwilling to deal with the horny
(i genuinely unsure why someone would want nsfw backgrounds on their console)
